version: "3"
services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=pepito1234
            - POSTGRES_DB=fastapi
        volumes:
            - postgres-volume:/var/lib/postgresql/data

    # alembic:
    #     build: .
    #     depends_on:
    #         - db

    api:
        depends_on:
            - db
        build: .
        restart: always
        ports:
            - 9000:9000
        volumes:
            - ./:/usr/src/app
        # env_file:
        #     - ./.env
        environment:
            - DATABASE_HOSTNAME=db
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=pepito1234
            - DATABASE_NAME=fastapi
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
        # command: uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload
        # command:
        #     [
        #         "sh",
        #         "-c",
        #         "alembic revision --autogenerate -m 'initial'; alembic upgrade head; uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload"
        #     ]
volumes:
    postgres-volume: # driver: local
