"""initial

Revision ID: 17dff2df6b51
Revises: 9236cfc71a7f
Create Date: 2023-03-31 08:19:57.497788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17dff2df6b51'
down_revision = '9236cfc71a7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
