"""initial

Revision ID: 55b5bec0cd87
Revises: db3cef52c2b1
Create Date: 2023-03-31 04:02:38.275406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b5bec0cd87'
down_revision = 'db3cef52c2b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
