"""initial

Revision ID: 569264df1692
Revises: f65a8d3d8f04
Create Date: 2023-03-31 08:53:33.644076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569264df1692'
down_revision = 'f65a8d3d8f04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
