"""initial

Revision ID: 6965cac5c35b
Revises: 17dff2df6b51
Create Date: 2023-03-31 08:22:01.367804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6965cac5c35b'
down_revision = '17dff2df6b51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
