"""initial

Revision ID: 9236cfc71a7f
Revises: 55b5bec0cd87
Create Date: 2023-03-31 08:13:24.534789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9236cfc71a7f'
down_revision = '55b5bec0cd87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
