"""initial

Revision ID: e863ad3b5a90
Revises: f5f3961a30b7
Create Date: 2023-04-02 14:45:58.020965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e863ad3b5a90'
down_revision = 'f5f3961a30b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
