"""initial

Revision ID: f65a8d3d8f04
Revises: 6965cac5c35b
Create Date: 2023-03-31 08:50:50.379944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65a8d3d8f04'
down_revision = '6965cac5c35b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
